/**
 *Each new term in the Fibonacci sequence is generated by adding the previous two terms.
 *By starting with 1 and 2, the first 10 terms will be:
 *
 *1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
 *
 *By considering the terms in the Fibonacci sequence whose values do not exceed four million,
 *find the sum of the even-valued terms.
 */
public class Even_Fibonacci_numbers {
    final static int Highest_Numeber = 4000000;
    public static void main(String[] args) {
        int next=0,sum=0;
        int first=1, second=1;
        next=nextFib(first,second);
        while (next<Highest_Numeber){
            if(next%2 == 0)
            {
                sum+=next;
            }
            first=second;
            second=next;
            next=nextFib(first,second);
        }

        System.out.println("The final Sum value for even number for terms under "+Highest_Numeber+" is: "+sum);
    }

    public static int nextFib(int first, int second){
        return first + second;
    }
}
